#!/usr/bin/env node
/**
 * TextBomb Setup Script
 * Run once after cloning: node scripts/setup.js
 * Creates .env with auto-generated secrets
 */
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(r => rl.question(q, r));

async function main() {
  console.log('\n🚀 TextBomb Setup\n' + '─'.repeat(40));

  const envPath = path.join(__dirname, '../server/.env');
  if (fs.existsSync(envPath)) {
    const overwrite = await ask('⚠️  server/.env already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') { console.log('Skipped.'); rl.close(); return; }
  }

  const dbUrl = await ask('PostgreSQL URL [postgresql://postgres:password@localhost:5432/textbomb]: ');
  const redisUrl = await ask('Redis URL [redis://localhost:6379]: ');
  const port = await ask('Server port [5000]: ');
  const clientUrl = await ask('Frontend URL [http://localhost:3000]: ');
  const metaSecret = await ask('Meta App Secret (from developers.facebook.com) [leave blank to fill later]: ');
  const webhookToken = await ask('Webhook verify token [textbomb-webhook]: ');

  const gen = () => crypto.randomBytes(32).toString('hex');

  const env = `# TextBomb Environment — generated by setup.js
# Edit this file to update your configuration

PORT=${port || '5000'}
NODE_ENV=development

DATABASE_URL=${dbUrl || 'postgresql://postgres:password@localhost:5432/textbomb'}
REDIS_URL=${redisUrl || 'redis://localhost:6379'}

JWT_SECRET=${gen()}
JWT_REFRESH_SECRET=${gen()}
JWT_EXPIRE=24h
JWT_REFRESH_EXPIRE=7d

ENCRYPTION_KEY=${gen()}

META_APP_SECRET=${metaSecret || 'replace_with_meta_app_secret'}
META_WEBHOOK_VERIFY_TOKEN=${webhookToken || 'textbomb-webhook'}
META_GRAPH_API_VERSION=v18.0

CLIENT_URL=${clientUrl || 'http://localhost:3000'}
`;

  fs.writeFileSync(envPath, env);
  console.log('\n✅ server/.env created with auto-generated secrets');
  console.log('\nNext steps:');
  console.log('  1. npm run install:all   ← install all dependencies');
  console.log('  2. npm run dev           ← start both servers');
  console.log('  3. Open http://localhost:3000/signup');
  console.log('\n  Or start them separately:');
  console.log('  Terminal 1: cd server && node index.js');
  console.log('  Terminal 2: cd client && npm start\n');

  rl.close();
}

main().catch(e => { console.error(e); rl.close(); process.exit(1); });
